import { prisma } from '@/lib/prisma';

export async function listConversations(userId: string) {
  return prisma.conversation.findMany({ where: { userId }, orderBy: { updatedAt: 'desc' } });
}

export async function createConversation(userId: string, title: string, modelKey: string, systemPrompt?: string) {
  return prisma.conversation.create({ data: { userId, title, modelKey, systemPrompt, titleAutoGenerated: true } });
}

export async function updateConversation(id: string, userId: string, data: { title?: string; systemPrompt?: string }) {
  return prisma.conversation.update({
    where: { id, userId },
    data: {
      ...data,
      ...(data.title ? { titleAutoGenerated: false } : {}),
    },
  });
}

export async function deleteConversation(id: string, userId: string) {
  return prisma.conversation.delete({ where: { id, userId } });
}

export function buildAutoTitleFromFirstMessage(content: string) {
  const normalized = content.replace(/\s+/g, ' ').trim();
  const hasCjk = /[\u3400-\u9FFF]/.test(normalized);
  const limit = hasCjk ? 20 : 40;
  if (normalized.length <= limit) return normalized || '新对话';
  return `${normalized.slice(0, limit)}...`;
}

export async function maybeAutoRenameConversation(conversationId: string, userId: string, firstMessage: string) {
  const conv = await prisma.conversation.findFirst({ where: { id: conversationId, userId } });
  if (!conv || !conv.titleAutoGenerated) return conv;
  return prisma.conversation.update({
    where: { id: conversationId },
    data: { title: buildAutoTitleFromFirstMessage(firstMessage), titleAutoGenerated: true },
  });
}
