-- CreateTable
CREATE TABLE "AiChannel" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "baseUrl" TEXT NOT NULL,
    "apiKey" TEXT NOT NULL,
    "defaultGroup" TEXT,
    "enabled" BOOLEAN NOT NULL DEFAULT true,
    "priority" INTEGER NOT NULL DEFAULT 0,
    "timeoutMs" INTEGER NOT NULL DEFAULT 60000,
    "remark" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "AiChannel_pkey" PRIMARY KEY ("id")
);

-- AlterTable
ALTER TABLE "AiModel" ADD COLUMN "channelId" TEXT;

-- AlterTable
ALTER TABLE "Conversation" ADD COLUMN "titleAutoGenerated" BOOLEAN NOT NULL DEFAULT true;

-- CreateIndex
CREATE UNIQUE INDEX "AiChannel_name_key" ON "AiChannel"("name");

-- CreateIndex
CREATE INDEX "AiChannel_enabled_priority_idx" ON "AiChannel"("enabled", "priority");

-- CreateIndex
CREATE INDEX "AiModel_channelId_idx" ON "AiModel"("channelId");

-- AddForeignKey
ALTER TABLE "AiModel" ADD CONSTRAINT "AiModel_channelId_fkey" FOREIGN KEY ("channelId") REFERENCES "AiChannel"("id") ON DELETE SET NULL ON UPDATE CASCADE;
